name: MarkyCraft
main: me.Markyroson.MarkyCraft.Main
version: 1.1
depend: [Vault]
commands:
    shop:
        description: Brings up shop GUI
    nav:
        description: Brings up navigator
    books:
        description: Brings up books GUI