name: MarkyCraft
main: me.Markyroson.MarkyCraft.Example
version: 1.0b
depend: [Vault]
commands:
    shop:
        description: Brings up shop GUI
    nav:
        description: Brings up navigator
    books:
        description: Brings up books GUI